### PR TITLE
Add new topics to the encyclopedia

### PR DESCRIPTION
**Pull request by Stark-Akshay**
### New Topics Added
NextJs, NodeJs, Sass, Micro Front End

### CODE REVIEW

**Comment by MedinavonLevetzow** [comment]
Great new topics! For sure following the card-structure within the newly proposed card.json file would be beneficial. Please have a detailed look on the PR #30

**Comment by Stark-Akshay** [comment]
@MedinavonLevetzow Thanks for the comment. I have some doubts to discuss with you on the same topic. Could we connect for a quick chat if possible at your convenience.

Thanks,
Akshay

**Comment by Buzzpy** [comment]
Hello there!
I'll assign the label `temporarily paused `for this PR, as we will soon be integrating Astro to this project and the content structure may change. Once it's ready, I'll give you an update.

Have a great day!

**Comment by Stark-Akshay** [comment]
Sure @Buzzpy , thanks for notifying me. Will wait for the update.

**Comment by Buzzpy** [comment]
Hello @Stark-Akshay !
Thanks for your patience! You can now close this PR, and create a new PR for the branch `astro-integration` following the guidelines in Issue #62 

This branch will be merged with the main branch as soon as possible and go live on the main webpage. Thanks a ton for contributing!

**Comment by Stark-Akshay** [comment]
Thanks for updating @Buzzpy , will do it soon!.

**Pull request closed without merging**
