### PR TITLE
Autocomplete search feature #9 v3 - Display Card content and Centered UI

### PR DESCRIPTION
**Pull request by Rodelph**
# What have i done / changed 

I have updated the functionality of the autocomplete where it allows you to display the card as a whole and no need to press the explain button as in the previous version. I have also made it so that it is centered in comparison where it used to show up on the left of the page. 

I also added a home button.

I was not able to fix the focus as discussed in issue #9. Maybe someone can help ?

# Is it tested ?
The feature is tested but might still need some tweaks.
Recording 2024-08-19 at 14 01 23

### CODE REVIEW

**Comment by Buzzpy** [comment]
Looks great. I will take a closer look at it as soon as possible!

Btw, what does that `Devldle` button do?

**Comment by Rodelph** [comment]
Ah I forgot to remove that. But basically it's a feature that I am going to create and test.

It's technically worldle but with the technical words that we have and I was thinking of creating that game with ranking of players. Devldle = Wordle

I still haven't done anything (backend wise) so it's just a button that u can remove from the hero.astro file. Let me know what you think about it.

**Comment by Buzzpy** [comment]
Oh got it! That'd be fun, I'd add it to the "future features" list. About the UI change on autocomplete search, I'd love to know @RayMathew's thoughts too!

Also, I don't know if it's already implemented, can we make arrow keys go up and down on autocomplete search suggestions? Like we do in Google? Is it a difficult task or an easy one even I can do?

**Comment by RayMathew** [comment]
I could try working on issue 9 after this MR is resolved and closed.

**Comment by Buzzpy** [comment]
> Cons:
> 
> * We're also changing the way website works. The user never again sees the list of all cards, even when going to the input box and emptying it. To be able to see the list of cards again, we've have had to add the Home button.
> * This also eliminates the behaviour of the original search, where on keyup the cards are gradually filtered.
> 
Well, that's something serious. I first loved how it doesn't need an explain button once the full term is searched but the fact user has to go back to the Home page makes it inconvenient. I think the previous method (already deployed one on [astro-devpedia.pages.dev](https://astro-devpedia.pages.dev)) is the best.

Would you agree, @Rodelph ?

**Comment by Rodelph** [comment]
Yes it does change the dynamic of the website. Since we don't want to follow this path then what we already have is good.

You can close this PR without merging.

**Pull request closed without merging**
