### PR TITLE
Filter by Category Feature

### PR DESCRIPTION
**Pull request by RayMathew**
Fixes https://github.com/Buzzpy/Dev-Encyclopedia/issues/18, fixes https://github.com/Buzzpy/Dev-Encyclopedia/issues/3, fixes https://github.com/Buzzpy/Dev-Encyclopedia/issues/116

Several things were done in this feature:
1. Data about the content/terms is needed by both `Hero` and `CardList` components. So the data is now fetched from the parent component `DevEncyclopedia` and passed to the child components as props.
2. In order for Filter by Category to work with and complement the Search feature, I had to move all the Search code to `Hero.astro` file.
3. I initially created the class `Hero extends HTMLElement` to be able to pass data to the `<script>` block. (Refer this https://docs.astro.build/en/guides/client-side-scripts/). Later on I saw it was not needed, but I left the class as it is, because I believe this is accurate of what Astro code should look like. Feel free to correct me.

About the feature:
1. When the user selects a category, it shows all the cards which fit that category (this part is obvious).
2. But also: when a category is selected, and the user searches by typing, the auto-complete now only shows search suggestions _for that category_.
3. If the user wants to go back to searching without a category, they can select "None".

Do you have suggestions?

P.S. I'm new to Typescript, so feel free to correct what I've done there too.

### CODE REVIEW

**Comment by Buzzpy** [comment]
That's really awesome, @RayMathew! It looks pretty great and really better than having a bunch of buttons. 
And it looks ready to be deployed, for me, should I merge or will you be adding some more commits?

**Review by Buzzpy — APPROVED** [review]

**Comment by RayMathew** [comment]
Thanks @Buzzpy  :) Yes, it's complete and ready to be deployed. I won't be adding further commits.

I might work on the enhancement of adding categories at the bottom of each modal in the near future, but I want to take a step back for a bit for now. I'm also around for bug fixes and reviews.

**Comment by Buzzpy** [comment]
Thanks a bunch! And please, don't be in a rush for those changes.

I guess we can close those issues now, right?

**Comment by RayMathew** [comment]
I would suggest testing the changes yourself first and see if you're satisfied before closing them :)

**Comment by RayMathew** [comment]
oh I guess they auto-close because of my 'fixes' comment.

**Comment by Buzzpy** [comment]
Oh yeah, but that's fine, I tested it locally too. And it's more than great for me!
And it's good to see those issues being gone too, haha!

Thanks again for your efforts and time! 🙏

**Comment by RayMathew** [comment]
awesome, my pleasure!

**Pull request merged**
