### PR TITLE
Refactoring UI

### PR DESCRIPTION
**Pull request by violentanirudh**
Use '/' to focus on Search Bar
Removed unwanted Scroll Bar from Modal
Minor UI Changes

### CODE REVIEW

**Comment by violentanirudh** [comment]
Extracted all definitions in a JSON File. Make it easier to add definitions.
```json
"conditionalStatement": {
    "heading": "Conditional Statement",
    "paragraphs": [
      "A statement that performs different actions based on whether a specified condition is true or false. Common conditional statements include if, else, and switch."
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/If-Then-Else-diagram.svg/330px-If-Then-Else-diagram.svg.png",
    "source": "https://www.geeksforgeeks.org/conditional-statements-in-programming/",
    "title": "Conditional Statement",
    "subtext": "Decisions in a program's flow."
  }
```
This file can be cached in localStorage which can be access anytime, even without internet.
Press '/' to search feature added.
Removed explain button, clicking on the card directly opens the modal.

**Comment by Buzzpy** [comment]
Hello!
UI looks fine, but I have to take some time to take a closer look.

However, putting all the definitions in a single JSON file isn't the go-to for this project. You see, as new terms are being added almost every day, this approach could slow down the retrieval and management of data. It could also make the file more prone to errors or conflicts when multiple updates are made simultaneously from different PRs.

On top of that, as the file grows larger, it could affect the performance of the system, making it harder to maintain and scale. So I'm afraid I can't approve this commit.

It must have been a very time-consuming task for you so thanks a bunch for thinking about others! 🤍

**Comment by violentanirudh** [comment]
Sure. I agree with the UI and one suggestion, let's add the function : pressing '/' would focus on search bar making it easier for user to search.

Single JSON File will be better option than a JavaScript Object to be used, and retrieval is fast because it consumes less space (then the JavaScript file itself) and is also cached on client side. 

image

Check out this image, that how you can add a simple definition (quite easy, as we know about dictionaries and objects). Adding definitions in the main script.js file won't be a good practice.

**Comment by Sudharshaun** [comment]
Hey @violentanirudh , I understand what you are telling here. 
Please refer the branch [astro-integration](https://github.com/Buzzpy/Dev-Encyclopedia/tree/astro-integration). The site is right now in the transition from Vannila JS to Astro JS. We have used JSON file based data retreival for each topic. 

If you'd like to add the search functionality please feel free to make changes and raise a PR to `astro-integration` branch. Thanks ❤️

**Comment by Buzzpy** [comment]
@Sudharshaun is right, @violentanirudh. The branch `astro-integration` is the branch that'd be used for all new changes, and it's deployed on [astro-devpedia.pages.dev](https://astro-devpedia.pages.dev/) for now. Take a look, and if you'd like to add more changes, create a PR to `astro-integration` branch 🚀

I'll close the PR without merging, please feel free to create a new PR on the new branch including the search functionality. Thanks a ton for contributing!

**Pull request closed without merging**
