### PR TITLE
Feat anki

### PR DESCRIPTION
**Pull request by DChrispim**
Objective: Automatically creates flashcards deck (for Anki) from the dev terms (title and description text) so that students can study them.

Implemented features:
- Created Python script `auto_anki_card_creation.py` that uses the dev terms to create flashcards for Anki. Each card as a question that uses the `title` (i.e.  `"title": "ACID Transactions"` creates `What is ACID Transactions?`) and the text from `"description":"text"` as the answer (the answer for the previous examples is `ACID (Atomicity, Consistency, Isolation, Durability) transactions ensure that database operations are processed reliably. Think of ACID transactions as a checklist that guarantees every financial transaction is processed completely and accurately.`). Each term is used to create one card, all cards are added to the Anki deck and the file is saved on `/src/content
/anki_deck/deck.apkg`.
- Included a download button on hero page to download `deck.apkg`.
- Create automatization GitHub workflow (file `/.github/workflows/`) that automatically run the Python script every time the branches main, or develop, receives modifications (push) that alters the filed in the folder `src/content/terms/**`. In order to this workflow to work, the repository must authorize the Workflow permissions to Read and write permissions. If the commit is successful, a new commit will be added by `github-actions[bot]` with the message `Add files generated by auto_anki_card_creation.py. Check src/content/anki_deck.`

### CODE REVIEW

**Comment by Buzzpy** [comment]
Thanks for your efforts and time! Although I'm not quite sure on the Anki deck feature, I will give it a try.

@RayMathew, @KC900201 Any thoughts?

**Comment by KC900201** [comment]
@Buzzpy, sorry. I don't have any prior knowledge on the anki feature as well.

Upon looking at the commit description, there are usages of Python script. Will look into that later

**Comment by RayMathew** [comment]
Anki is a popular 3rd party flashcard tool. https://apps.ankiweb.net/. You can create decks of flashcards on any topic. In case you haven't heard of flashcards before, https://en.wikipedia.org/wiki/Flashcard.

I haven't looked at the code, but I find the idea is impressive, how it auto-updates the flashcards.

**I don't find the idea of having flashcards in itself useful, because these are not terms that you should memorize or be tested on**. Dev Encyclopedia is just a reference. But if other's feel differently, please go ahead.

**Comment by KC900201** [comment]
I agree with @RayMathew's point that adding an **Anki** flashcard feature is not part of the main objective for this project, but rather a personal preference if the user wishes to familiarize himself with the available terms introduced in the dev encyclopedia. 

@Buzzpy it would be more reasonable for you to decide whether to add this optional feature or not. In my opinion, I would emphasize more on the pagination feature and introducing database structure for the project

**Comment by Buzzpy** [comment]
I see. And I agree with your views about the purpose of the website. The flashcard feature would make a whole new website, and it isn't applicable to an encyclopedia like this. 

However, this was a great suggestion, and thanks a lot for your time and efforts, @DChrispim! This got my attention, there could be a flashcard version of the website in the future!

**Pull request closed without merging**
