### PR TITLE
Hardcode HTML to Dynamic JSON

### PR DESCRIPTION
**Pull request by Brajo280603**
removed hardcoded html cards and modals, converted all data to json , 

the function createCards in script.js is used to create cards dynamically from ./data/cards.json

updated the function showModal to generate the modal informations directly from the imported json file.

This will result in easier addition of new cards and modification of old cards.

also as each data is now in JSON additional parameters can be added to improve search functionalities , as mentioned in   #3 

This is tested with github pages

### CODE REVIEW

**Comment by Suryakant01** [comment]
this is definitely better than previous method , it makes the code clean

**Comment by Brajo280603** [comment]
A Scraper has been added to helpers/ folder to easily convert current cards to json

**Comment by MedinavonLevetzow** [comment]
Hi I have resolved the issues with this merge conflict on my PR #41  as this is the base-branch I used, you can directly benefit from this without needing to resolve the conflicts on your own, hope this helps a bit :)

**Comment by Ibrahim-Faisal15** [comment]
I think it's better to just to write the complete codebase in a better manageable framework for future ease.

**Pull request closed without merging**
